export enum ListingType {
  LOCAL_ADULT_ONETIME = "LOCAL_ADULT_ONETIME",
  LOCAL_STUDENT_ONETIME = "LOCAL_STUDENT_ONETIME",
  LOCAL_SENIOR_ONETIME = "LOCAL_SENIOR_ONETIME",
  FOREIGNER_ONETIME = "FOREIGNER_ONETIME",
  ANNUALPASS = "ANNUALPASS",
}
