export enum ListingType {
  LOCAL_ADULT_ONETIME = "LOCAL_ADULT_ONETIME",
  LOCAL_STUDENT_ONETIME = "LOCAL_STUDENT_ONETIME",
  LOCAL_SENIOR_ONETIME = "LOCAL_SENIOR_ONETIME",
  LOCAL_CHILD_ONETIME = "LOCAL_CHILD_ONETIME",
  FOREIGNER_ADULT_ONETIME = "FOREIGNER_ADULT_ONETIME",
  FOREIGNER_CHILD_ONETIME = "FOREIGNER_CHILD_ONETIME",
  FOREIGNER_ANNUAL_PASS = "FOREIGNER_ANNUAL_PASS",
  LOCAL_ANNUAL_PASS = "LOCAL_ANNUAL_PASS",
}
